set(RRSPH_FIO_DIR CACHE PATH "RRSPH_FIO directory")


find_path(RRSPH_FIO_INCLUDE_DIR RRSPH_FIO.h
  HINTS "${RRSPH_FIO_DIR}/include"
)

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(VC_LIB_PATH_SUFFIX lib/x64)
else()
  set(VC_LIB_PATH_SUFFIX lib/x86)
endif()

find_library(RRSPH_FIO_LIBRARY
  NAMES RRSPH_FIO
  HINTS ${RRSPH_FIO_DIR}
  PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

find_library(RR_LIBRARY
  NAMES RR
  HINTS ${RRSPH_FIO_DIR}
  PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

find_library(RRSPH_PARAMS_LIBRARY
  NAMES RRSPH_PARAMS
  HINTS ${RRSPH_FIO_DIR}
  PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RRSPH_FIO
                                  REQUIRED_VARS RRSPH_FIO_LIBRARY RRSPH_FIO_INCLUDE_DIR RR_LIBRARY RRSPH_PARAMS_LIBRARY)


set(RRSPH_FIO_INCLUDE_DIRECTORIES ${RRSPH_FIO_INCLUDE_DIR})
set(RRSPH_FIO_LIBRARIES ${RRSPH_FIO_LIBRARY} ${RR_LIBRARY} ${RRSPH_PARAMS_LIBRARY})