set(SPH2D_FIO_DIR CACHE PATH "SPH2D_FIO directory")


find_path(SPH2D_FIO_INCLUDE_DIR SPH2D_FIO.h
  HINTS "${SPH2D_FIO_DIR}/include"
)

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(VC_LIB_PATH_SUFFIX lib/x64)
else()
  set(VC_LIB_PATH_SUFFIX lib/x86)
endif()

find_library(SPH2D_FIO_LIBRARY
  NAMES SPH2D_FIO
  HINTS ${SPH2D_FIO_DIR}
  PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

find_library(RR_LIBRARY
  NAMES RR
  HINTS ${SPH2D_FIO_DIR}
  PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

find_library(SPH2D_PARAMS_LIBRARY
  NAMES SPH2D_PARAMS
  HINTS ${SPH2D_FIO_DIR}
  PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPH2D_FIO
                                  REQUIRED_VARS SPH2D_FIO_LIBRARY SPH2D_FIO_INCLUDE_DIR RR_LIBRARY SPH2D_PARAMS_LIBRARY)


set(SPH2D_FIO_INCLUDE_DIRECTORIES ${SPH2D_FIO_INCLUDE_DIR})
set(SPH2D_FIO_LIBRARIES ${SPH2D_FIO_LIBRARY} ${RR_LIBRARY} ${SPH2D_PARAMS_LIBRARY})